//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnicodeBackEnd.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<SP_GetOrgnization_Result> SP_GetOrgnization()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetOrgnization_Result>("SP_GetOrgnization");
        }
    
        public virtual ObjectResult<SP_GetRegions_Result> SP_GetRegions(Nullable<decimal> orgID)
        {
            var orgIDParameter = orgID.HasValue ?
                new ObjectParameter("OrgID", orgID) :
                new ObjectParameter("OrgID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetRegions_Result>("SP_GetRegions", orgIDParameter);
        }

        public System.Data.Entity.DbSet<UnicodeBackEnd.Models.SP_GetOrgnization_Result> SP_GetOrgnization_Result { get; set; }

        public System.Data.Entity.DbSet<UnicodeBackEnd.Models.SP_GetRegions_Result> SP_GetRegions_Result { get; set; }
    }
}
